// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvMgbvCBUe0IJ34-0uEZ3-SFyzfpGwLR8',
    appId: '1:717834521409:web:0e83e2751fd54c0e2c6fc0',
    messagingSenderId: '717834521409',
    projectId: 'shiv-e0361',
    authDomain: 'shiv-e0361.firebaseapp.com',
    storageBucket: 'shiv-e0361.firebasestorage.app',
    measurementId: 'G-GTEXJPQ0TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewqMvSxvEm-qZs8n_5UNiXKbdDfNcSPE',
    appId: '1:717834521409:android:10d016eab1266f0e2c6fc0',
    messagingSenderId: '717834521409',
    projectId: 'shiv-e0361',
    storageBucket: 'shiv-e0361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMiA6DyQMj34Odd-9L_TOxEClkYJV9JS4',
    appId: '1:717834521409:ios:da925637f9c3efbf2c6fc0',
    messagingSenderId: '717834521409',
    projectId: 'shiv-e0361',
    storageBucket: 'shiv-e0361.firebasestorage.app',
    iosBundleId: 'com.example.shivPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMiA6DyQMj34Odd-9L_TOxEClkYJV9JS4',
    appId: '1:717834521409:ios:da925637f9c3efbf2c6fc0',
    messagingSenderId: '717834521409',
    projectId: 'shiv-e0361',
    storageBucket: 'shiv-e0361.firebasestorage.app',
    iosBundleId: 'com.example.shivPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvMgbvCBUe0IJ34-0uEZ3-SFyzfpGwLR8',
    appId: '1:717834521409:web:f1a37a1de5d840082c6fc0',
    messagingSenderId: '717834521409',
    projectId: 'shiv-e0361',
    authDomain: 'shiv-e0361.firebaseapp.com',
    storageBucket: 'shiv-e0361.firebasestorage.app',
    measurementId: 'G-M75KM60FX8',
  );
}
